services:
  app:
    build:
      context: .
      args:
        OPENAI_API: ${OPENAI_API}
    ports:
      - "3007:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ALLOWED_ORIGINS=http://localhost:3007,http://127.0.0.1:3007
